### ISSUE TITLE
[Question Service] Integration issues and clarifications

### ISSUE THREAD

**Issue by c0j0s** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#32]
Below are some complications faced during integration:

### Issues: 
- [x] mongodb not in backend package.json? module not found when starting service.
- [ ] allow more char for question description.
with the addition of a rich text editor, adding images can easily exceed the current word limit. Need help to relax the limit.
<img width="315" alt="image" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/7760148/9c3acc78-162b-4d91-a617-01fa844833f9">
<img width="403" alt="image" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/7760148/6c0b0a4f-4e83-4406-b794-465698246f36">

### Clarifications: 
- [ ] question id or _id? 
the assignment seems to follow the leetcode style of using natural numbers for question id, the backend is currently using the MongoDB way of keeping ids. So which style should we follow moving ahead?
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/7760148/ccb8ea83-815f-42e6-b064-8f0ca7cf0045)  ![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/7760148/3aa66c66-1b1b-4fdf-9f77-57a3be0aa535)
- [x] Structure of response format
  The question data is currently nested in a separate question field:
  ```
  {
      _id:
      question: {
           ...
      }
  }
  ``` 
  Can the backend return flattened format? else the frontend have to implement a separate type to match the structure.
  ```
  {
      id:
      title:
      ...
  }
  ``` 
- [x] Separation of examples and constraints from the description.
Do we want to split the fields? It's manageable for now, but we might face issues if we are going to implement assignment 6 (leetcode crawler)

**Comment by tryyang2001** [comment]
@xingjie99 Looks like you forgot to update [package.json](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/pull/29/files#diff-b7dd81911dddf361654402a7e845962743c85abad204ce2876397df80eb455b5L14) for MongoDB? Also, are we using `mongoose`? I thought that one was easier and cleaner?

> So which style should we follow moving ahead?

Hmm, first I don't think we need to ask the user to give a question id. Second, I think it is better to have an alphanumeric id instead of just pure integer id so that it is less likely to have collision? But for the question id to display to the user, I assume we need to show them in number. But, I was assuming this rendering integer question id will be handled on the frontend, as you can get all questions from the API call in an array format, then you just display the index of each question?

> Can the backend return flattened format?

I apologise for this inconvenience (I didn't review the code carefully...). And the answer is YES. My intention is to return single question directly, without the `question:` field. I will update this later, give me some time!

> Do we want to split the fields? It's manageable for now, but we might face issues if we are going to implement assignment 6 (leetcode crawler)

Hmm interesting. Currently I am more prone to separate `examples` and `constraints` from `description`. I have gone through assignment 6 requirements, but I am clueless right now how we can do this... Do you have any idea in your mind now? If we are able to pass question from third-party source, then do you think we can further process this data to extract examples and constraints from the description? The benefits of separating them is that it is much easier to render nicely on frontend I guess? Let me know if you have different opinions! :D

**Comment by c0j0s** [comment]
1. leetcode uses the integer id for their questions, I can generate the numbering in the frontend but my concern is that if we were to sync the questions from leetcode, would it be easier to cross reference if we uses the same id system. i'm fine with either approach.
2. 👍
3. No idea right now, the approach depends on what access we have to leetcode system. Anyway, we are not required to upload all questions from leetcode then I guess splitting it or not wouldn't make much difference. Since you already set it up, i'll modify my frontend accordingly.

thankss

**Comment by tryyang2001** [comment]
> leetcode uses the integer id for their questions, I can generate the numbering in the frontend but my concern is that if we were to sync the questions from leetcode, would it be easier to cross reference if we uses the same id system. i'm fine with either approach.

Actually, this is a very good point. At first, I thought it would be hard to keep track of how many questions we have already inserted and what should be the next question id if we store the id in integer format. But then if we are going to use leetcode questions, then I can assume that we always know what the question id is, so I think it is fine to use an integer id now. Any idea from @xingjie99 @weidak and @tlyi ?

**Comment by weidak** [comment]
> > leetcode uses the integer id for their questions, I can generate the numbering in the frontend but my concern is that if we were to sync the questions from leetcode, would it be easier to cross reference if we uses the same id system. i'm fine with either approach.
> 
> Actually, this is a very good point. At first, I thought it would be hard to keep track of how many questions we have already inserted and what should be the next question id if we store the id in integer format. But then if we are going to use leetcode questions, then I can assume that we always know what the question id is, so I think it is fine to use an integer id now. Any idea from @xingjie99 @weidak and @tlyi ?

I think its kind of wonky if we add a question with ID 1 and ID 3 one by one because our table will look like:
1) Two Sum
3) Longest substring...
Tbh i suggested integers for ID at the start is because its faster to computer/match integers than alphanumerics but in the grand scheme of things it doesn't matter. I personally would rather we come up with our own ID system, and have a flexibility to restrict it later on to make our lives much easier for now

**Comment by xingjie99** [comment]
>Any idea from @xingjie99 @weidak and @tlyi ?

Can always include another column that is called `leetcode_id` or something if we really want to keep track of it. I dont think matching our database primary key id to the leetcode id makes a lot of sense (extra work needed to ensure that the ids are properly matched) like what @weidak mentioned above
