### ISSUE TITLE
[Question Service] Message value format in PUT response

### ISSUE THREAD

**Issue by c0j0s** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#39]
<img width="423" alt="image" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/7760148/f3db53e1-214f-420a-b934-764c06a61c84">

is stringified json the intended return format?
@tryyang2001 @xingjie99 

thanks

**Comment by tryyang2001** [comment]
Ermm so far I simply return the error message from Zod, so the message turns out to be stringified JSON. If you think we shouldn't return this kind of error message, I can modify it.

**Comment by tryyang2001** [comment]
I would like to know if you need to distinguish what kind of error you received from the API response. If so, I was thinking if I change the `error` field to something like `INPUT ERROR` for every error due to the request body input. Will this help? Or do you need the details about the error like the one you showed that it is because the input string is too small for a certain input?

The reason why I can't always give exact error message is because in `Zod`, sometimes the detailed error message does not always come from the `message` field, see an example here:
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/69421979/1434a016-b58a-4b5b-8cf6-f5b1ba58e8d0)
The error shown above says that the `input` filed is **required** when you provide the `examples`, but the `message` only says `required`. So you might not know what thing is required...

**Comment by c0j0s** [comment]
i see, the error message is detailed enough, just that the format is not that friendly. I'll do the parsing in frontend first for now.

**Comment by c0j0s** [comment]
if the message can return a simplified object like this:
```
{
  title: "title is missing"
  description: "description is missing"
}
```
i will be able to set error state to individual inputs, something like this:
```
<input 
      isInvalid={'title' in res.message}
      errorMessage={ res.message['title'] }
></input>
```
currently, I simply output all error messages in the same container which is not ideal if we have multiple errors.
