### ISSUE TITLE
Define pages for assignment 1/2

### ISSUE THREAD

**Issue by c0j0s** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#6]
### latest
```
root (AS1, home page/landing page)
├── /questions (AS1, showing a list of questions)
│   ├── /[id] (AS1, showing individual questions with more details)
│   └── /new (AS1, create new question)
├── /sign-in (AS2, typical login page)
├── /sign-up (AS2, tentative)
├── /user (AS2, showing user profile and account details)
└── /reset-password (AS2, tentative, page that handles the change password request)
    └── [token] (AS2, tentative, page that asks for new password)
```
A rough outline of the pages, what u guys think?

### old
```
root [assignment1] (landing page, show a table of questions)
- /question 
--- /{id} [future] (question details, update + delete function)
--- /new [assignment2] (creation of new questions)
- /login  [assignment2] (user registration)
- /user [assignment2] (landing page, show user profile, update + delete function)
```

**Comment by weidak** [comment]
Sure, this sounds good!

**Comment by tryyang2001** [comment]
Looks good to me as well, just some suggestions for more pages:
```
root (AS1, home page/landing page)
├── /questions (AS1, showing a list of questions)
│   ├── /[id] (AS1, showing individual questions with more details)
│   └── /new (AS1, create new question)
├── /sign-in (AS2, typical login page)
├── /sign-up (AS2, tentative)
├── /user (AS2, showing user profile and account details)
└── /reset-password (AS2, tentative, page that handles the change password request)
    └── [token] (AS2, tentative, page that asks for new password)
```
Also, I can recommend one tool that I frequently use to illustrate the path tree :P, check out this [link](https://tree.nathanfriend.io/).

**Comment by c0j0s** [comment]
Since we have our initial frontend structure in place, let us define our deliverables that we can start work on😄 

Here are some tasks based on the latest structure: 
1. declare user and question types (src/types)
1. base layout (src/app/layout)
   - nav, footer component
   - landing page (src/app/page) (no idea what to put here, can consider moving the signin component here?)
1. sign-in/up (src/app/signin/page)
   - sign-in/up page (can consider combining the pages)
1. user (src/app/user/page)
   - user profile
   - define dummy values (in constant/ folder ?)
1. questions page (src/app/questions/page)
   - table of questions
   - define dummy values (in constant/ folder ?)
 
As for the assignment, i guess we can split into 3 parts [1,2], [3,4] and [5] for the 3 for us?
You can choose which part to work on.

Also lets agree on a standard naming convention for our feature branches like: `frontend-<fetaure>`?


@weidak, @tlyi what u guys think?

**Comment by tlyi** [comment]
Thanks for organising the tasks @c0j0s! 😄 Just to clarify, the 3 parts [1,2], [3,4] and [5] refer to the tasks you have listed here, right?

For the landing page under task (ii), I think the home page could also contain an overview of completed/started/suggested questions. This is not under the scope of assignments, but it would be good to have a frontend mockup of it for now to fill the space. I think the features to be placed here would be clearer after we fully define our software requirements.

I'm good with the naming convention for the feature branch!

@weidak @c0j0s I think it would be good for us to have a meeting to decide on a theme and maybe work on the wireframes in the same document on Figma so that the pages are roughly standardised. 
Also, if no one else has any preference, i'm okay with working on tasks [i, ii]. 👍

**Comment by c0j0s** [comment]
> Thanks for organising the tasks @c0j0s! 😄 Just to clarify, the 3 parts [1,2], [3,4] and [5] refer to the tasks you have listed here, right?
> 
> For the landing page under task (ii), I think the home page could also contain an overview of completed/started/suggested questions. This is not under the scope of assignments, but it would be good to have a frontend mockup of it for now to fill the space. I think the features to be placed here would be clearer after we fully define our software requirements.
> 
> I'm good with the naming convention for the feature branch!
> 
> @weidak @c0j0s I think it would be good for us to have a meeting to decide on a theme and maybe work on the wireframes in the same document on Figma so that the pages are roughly standardised. Also, if no one else has any preference, i'm okay with working on tasks [i, ii]. 👍

1. Yes, it's referring to the tasks.
2. Definitely.
3. I'll take task 5 then.

**Comment by tryyang2001** [comment]
Hihi team, a few suggestions for the pages:

> 1. declare user and question types (src/types)

For this, I believe for now we couldn't really finalize the types and the attributes that we want, so I am suggesting for both frontend and backend, feel free to use whatever attributes that you need, and then we come out with a finalised structure when we start integration. 

> sign-in/up (src/app/signin/page)

We can fix the naming convention for our route. I will suggest using kebab-case (sign-in) since it is easier to read instead of lowercamelcase (signin). See if you all agree or have different opinion.

user 

> (src/app/user/page)

I believe since we have multiple users, we might want to consider using the link like `src/app/users/[userId]/page` instead of just `/user/page`. Same for `/question`. Any idea? Open for discussion.

> Also lets agree on a standard naming convention for our feature branches like: frontend-<feature>?

Not sure if each issue in GitHub has a ticket number? Like in Jira we can have ticket number like PROJ-1. We can consider using the `ticket_num` as part of the branch name. Suggestion for the ticket number: `FE` for frontend tickets, `BE` for backend tickets. Then, for the `feature`, we can use PascalCase as the naming convention and use underscore `_` to replace whitespace. An example will be: `FE1-Create_Navbar_And_Footer`. Any opinion? 

Also, I feel that there is a need to document all the convention and policies that we agreed in somewhere for easy reference. Where should we do this? Notion?

**Comment by c0j0s** [comment]
> Hihi team, a few suggestions for the pages:
> 
> > 1. declare user and question types (src/types)
> 
> For this, I believe for now we couldn't really finalize the types and the attributes that we want, so I am suggesting for both frontend and backend, feel free to use whatever attributes that you need, and then we come out with a finalised structure when we start integration.
> 
> > sign-in/up (src/app/signin/page)
> 
> We can fix the naming convention for our route. I will suggest using kebab-case (sign-in) since it is easier to read instead of lowercamelcase (signin). See if you all agree or have different opinion.
> 
> > (src/app/user/page)
> 
> I believe since we have multiple users, we might want to consider using the link with a [dynamic route](https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes) like `src/app/users/[userId]/page` instead of just `/user/page`. Same for `/question`. Any idea? Open for discussion.
> 
> > Also lets agree on a standard naming convention for our feature branches like: frontend-?
> 
> Not sure if each issue in GitHub has a ticket number? Like in Jira we can have ticket number like PROJ-1. We can consider using the `ticket_num` as part of the branch name. Suggestion for the ticket number: `FE` for frontend tickets, `BE` for backend tickets. Then, for the `feature`, we can use PascalCase as the naming convention and use underscore `_` to replace whitespace. An example will be: `FE1-Create_Navbar_And_Footer`. Any opinion?
> 
> Also, I feel that there is a need to document all the convention and policies that we agreed in somewhere for easy reference. Where should we do this? Notion? Google Docs?

1. We can start with what we have discussed in #5.
2. Sure
3. For questions we will use dynamic route for details page, but I don't see the reason for using  `/user/<userid>` as its guaranteed `/user` should only show logged-in user profile?
4. github can link branches with issue number like this:
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/7760148/cdf1e58e-eb2b-48a1-9192-de68fd65ded0)
branch name will be auto-generated, not sure if this is what you are looking for.

**Comment by tryyang2001** [comment]
> For questions we will use dynamic route for details page, but I don't see the reason for using /user/<userid> as its guaranteed /user should only show logged-in user profile?

One possible feature that I can think of for having a dynamic route for `user` is to let the user view others' profile. But ya, for the first 2 assignments, we don't really need to use dynamic route.

> github can link branches with issue number like this

Awesome, this is good, we can use this feature to create side branches. But we need to make sure we have a good and descriptive issue name so that the branch name will make sense. I am fine with any naming convention of the branch actually, just that I hope we can keep the same thing consistent :D

**Comment by weidak** [comment]
Ok sure I can take 3, 4. Thank you @c0j0s  for helping organize the things out, its really neat 👍🏻 👍🏻  Im thinking of having the sign-in/sign-up page as a drawer that slides in from the left/ride side, as well as the viewing of your own profile if you are already logged in so still not sure what to do with the landing page. As @tlyi suggests, I think we should at least plan out the flow/colors/theme of the app (on Figma or somewhere) before we commence so we have a clearer direction but the difficulty right now is finding a common time tgt... Otherwise, the issues/branches naming convention looks good too! 

As for @tryyang2001 I think these details (like kebab-case, dynamic routing) can be written down in notion's coding standards or meeting notes because we are still a ways away and will forget by then haha 😓

**Comment by weidak** [comment]
Closing this discussion thread to start making tickets/issues
