### ISSUE TITLE
[Auth] Support for Server Side Pages

### ISSUE THREAD

**Issue by c0j0s** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#73]
Currently, the authContext is processed in the client side. which would cause issues for server-side pages like the question page.
<img width="583" alt="image" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g05/assets/7760148/c3368ca9-4cb7-48dc-ac2b-e340132be400">

After reading [authenticating-server-rendered-pages](https://nextjs.org/docs/pages/building-your-application/routing/authenticating#authenticating-server-rendered-pages), would like to know if session will be supported in the current auth pattern.

Thankss

**Comment by tlyi** [comment]
We are planning to use JWT authentication, which would require us to store the token somewhere on the browser, and in the current implementation, we were planning to store it in local storage, which would require client-side rendering. I did a quick search on this and it seems we can use server-side rendering if we store the JWT in cookies instead. However, it is not as straightforward since the JWT strategy in passport.js does not support it directly (but I think it can be done?), and we were not planning to use Next-Auth since we want to run Auth Service separately.  

Just curious, is there any strong reason for us to use server-side rendering? If we want to stick to server-side rendering, then I will relook at the implementation for the JWT and the AuthContext. @c0j0s @tryyang2001

**Comment by tryyang2001** [comment]
Oh from my past experience of using Next-Auth, the JWT token is stored in the cookies, so this does not have any impact on server-side components. I think it is better to store it in the cookies though.

> is there any strong reason for us to use server-side rendering

The two main reasons I can think of is the speed and efficiency. Client-side rendering is very slow, especially when we have a large content to load (which is our case for question detail page). There will be a huge rendering speed difference if the question detail page is client component vs server component. Of course we can do caching to make subsequent page loading becomes much faster, but the first load without the cache is always slow. Also, if the page has no user-interaction needed, which is also the case for our question detail page, then I think the best is to do SSR.

**Comment by tlyi** [comment]
Okay, I'll change to the cookie way and also utilise `getServerSideProps` for auth in order to support server-side rendering. Did not really look into server side rendering, so thank you @c0j0s and @tryyang2001 for bringing it up! 😄

**Comment by tryyang2001** [comment]
Thank you, and btw the above Next-Auth function is just an example that I want to show haha, feel free to find any other alternatives to achieve the same result!

**Comment by c0j0s** [comment]
Seems like this has been resolved in #105
