### ISSUE TITLE
CollabContext breaks question details page

### ISSUE THREAD

**Issue by c0j0s** [CS3219-AY2324S1/ay2324s1-course-assessment-g05#95]
Currently question details page reuses `ProblemDescription`
```ts
<ProblemDescription question={question} />
```

`question` prop was removed and uses collab context instead
```ts
const ProblemDescription: FC = () => {
  const { question } = useCollabContext();

  if (!question) return;
....
```

Question. is there a reason why context is used in `ProblemDescription`, seems like using context would couple the component to a specific use case.

**Comment by tlyi** [comment]
Oh, sorry!! Since `ProblemDescription` was under the `collab` components folder, I thought it was only being used by the `ProblemPanel` inside the collaboration page, I didn't notice that the normal questions detail page was using it as well.

In this case, I agree that we should add back to the `question` prop and pass down the prop for the use case in the `collab` page instead. However, I think the `ProblemDescription` should be moved to the `question` components folder because it is confusing this way. 

@tryyang2001 If you are okay with it, can I just change this on your current branch before merging?

**Comment by tryyang2001** [comment]
Ah yes, feel free to move it  and update the code, thank you!
